name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update && sudo apt-get install gnucobol
      - run: |
          cd /tmp
          git clone --branch v1.4 https://github.com/opensourcecobol/Open-COBOL-ESQL.git
          cd Open-COBOL-ESQL
          autoreconf --force --install --verbose
          ./configure
          make
          sudo make install
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_cobol_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: ocesql example.cbl example.cob
      - run: cobc -x -locesql example.cob
        env:
          COBCPY: /usr/local/share/open-cobol-esql/copy
      - run: ./example
        env:
          LD_PRELOAD: /usr/local/lib/libocesql.so
